export type Axis = "TIME" | "ENERGY" | "VALUE" | "STRATEGY";
export type Group = "STANDARD" | "REVERSE" | "SITUATION";

export interface Question {
  id: number;
  axis: Axis;
  group: Group;
  text: string;
}

export const questions: Question[] = [
  // TIME 1-36
  { id: 1, axis: "TIME", group: "STANDARD", text: "지금 불편하더라도 미래에 도움이 된다면 그 선택을 한다." },
  { id: 2, axis: "TIME", group: "STANDARD", text: "현재의 만족보다 장기적인 방향이 더 중요하다." },
  { id: 3, axis: "TIME", group: "STANDARD", text: "오늘의 선택이 몇 년 뒤 나에게 어떤 영향을 줄지 자주 생각한다." },
  { id: 4, axis: "TIME", group: "STANDARD", text: "당장 성과가 없어도 방향이 맞으면 계속 간다." },
  { id: 5, axis: "TIME", group: "STANDARD", text: "미래의 나를 위해 현재를 조정하는 편이다." },
  { id: 6, axis: "TIME", group: "STANDARD", text: "지금 편한 길보다 나중에 의미 있는 길을 택한다." },
  { id: 7, axis: "TIME", group: "STANDARD", text: "단기 성과보다 장기 성장을 더 신뢰한다." },
  { id: 8, axis: "TIME", group: "STANDARD", text: "미래 목표가 분명할수록 현재의 불편함을 견딘다." },
  { id: 9, axis: "TIME", group: "STANDARD", text: "오늘의 기분보다 내일의 결과를 더 고려한다." },
  { id: 10, axis: "TIME", group: "STANDARD", text: "지금의 희생이 미래의 자유로 이어진다고 믿는다." },
  { id: 11, axis: "TIME", group: "STANDARD", text: "장기 계획이 없는 삶은 불안하게 느껴진다." },
  { id: 12, axis: "TIME", group: "STANDARD", text: "미래의 가능성이 크면 현재의 안정은 포기할 수 있다." },
  { id: 13, axis: "TIME", group: "REVERSE", text: "미래를 위해 지금을 희생하는 건 과하다고 느낀다." },
  { id: 14, axis: "TIME", group: "REVERSE", text: "지금 만족스럽다면 굳이 바꿀 필요를 못 느낀다." },
  { id: 15, axis: "TIME", group: "REVERSE", text: "먼 미래보다 오늘 하루가 더 중요하다." },
  { id: 16, axis: "TIME", group: "REVERSE", text: "장기 계획보다는 즉각적인 결과가 필요하다." },
  { id: 17, axis: "TIME", group: "REVERSE", text: "미래는 불확실하니 현재를 즐기는 게 낫다." },
  { id: 18, axis: "TIME", group: "REVERSE", text: "지금 행복하지 않으면 미래도 의미 없다고 느낀다." },
  { id: 19, axis: "TIME", group: "REVERSE", text: "나중 일을 고민하면 현재가 피곤해진다." },
  { id: 20, axis: "TIME", group: "REVERSE", text: "당장 성과가 없으면 그 선택은 틀린 것 같다." },
  { id: 21, axis: "TIME", group: "REVERSE", text: "미래보다 현재의 안정이 더 중요하다." },
  { id: 22, axis: "TIME", group: "REVERSE", text: "오늘의 편안함을 포기하고 싶지 않다." },
  { id: 23, axis: "TIME", group: "REVERSE", text: "장기 목표는 자주 바뀌니 크게 신경 쓰지 않는다." },
  { id: 24, axis: "TIME", group: "REVERSE", text: "지금을 희생하는 선택은 내 성향이 아니다." },
  { id: 25, axis: "TIME", group: "SITUATION", text: "쉬는 것보다 미래에 도움이 되는 일을 택한다." },
  { id: 26, axis: "TIME", group: "SITUATION", text: "즉각적 보상보다 나중의 이득을 고른다." },
  { id: 27, axis: "TIME", group: "SITUATION", text: "안정적인 선택보다 성장 가능성을 본다." },
  { id: 28, axis: "TIME", group: "SITUATION", text: "오늘의 피로보다 내일의 결과를 중시한다." },
  { id: 29, axis: "TIME", group: "SITUATION", text: "재미없어도 장기적으로 의미 있으면 계속한다." },
  { id: 30, axis: "TIME", group: "SITUATION", text: "지금 편한 선택과 나중에 유리한 선택이 충돌하면 후자를 고른다." },
  { id: 31, axis: "TIME", group: "SITUATION", text: "당장 결과가 없어도 방향이 맞으면 기다린다." },
  { id: 32, axis: "TIME", group: "SITUATION", text: "여유 시간이 생기면 미래를 위한 일에 쓴다." },
  { id: 33, axis: "TIME", group: "SITUATION", text: "내일 해도 될 일이라도 오늘 처리하는 편이다." },
  { id: 34, axis: "TIME", group: "SITUATION", text: "즉흥보다 계획을 선호한다." },
  { id: 35, axis: "TIME", group: "SITUATION", text: "현재의 만족보다 장기적 자유를 택한다." },
  { id: 36, axis: "TIME", group: "SITUATION", text: "지금의 안정이 미래를 제한하면 불안하다." },
  
  // ENERGY 37-72
  { id: 37, axis: "ENERGY", group: "STANDARD", text: "혼자 생각할 때 가장 에너지가 난다." },
  { id: 38, axis: "ENERGY", group: "STANDARD", text: "깊이 몰입하는 시간이 필요하다." },
  { id: 39, axis: "ENERGY", group: "STANDARD", text: "내면이 정리돼야 행동할 수 있다." },
  { id: 40, axis: "ENERGY", group: "STANDARD", text: "혼자 있는 시간이 생산적이다." },
  { id: 41, axis: "ENERGY", group: "STANDARD", text: "중요한 결정은 혼자 숙고한 뒤 내린다." },
  { id: 42, axis: "ENERGY", group: "STANDARD", text: "생각이 정리되면 에너지가 회복된다." },
  { id: 43, axis: "ENERGY", group: "STANDARD", text: "보여주기보다 이해하는 게 중요하다." },
  { id: 44, axis: "ENERGY", group: "STANDARD", text: "내 기준이 분명해야 움직인다." },
  { id: 45, axis: "ENERGY", group: "STANDARD", text: "조용한 환경에서 집중이 잘 된다." },
  { id: 46, axis: "ENERGY", group: "STANDARD", text: "사람을 많이 만나면 피로가 쌓인다." },
  { id: 47, axis: "ENERGY", group: "STANDARD", text: "내면의 납득이 외부 반응보다 중요하다." },
  { id: 48, axis: "ENERGY", group: "STANDARD", text: "고독한 시간이 성장에 필요하다." },
  { id: 49, axis: "ENERGY", group: "REVERSE", text: "사람들과 함께 있을 때 에너지가 난다." },
  { id: 50, axis: "ENERGY", group: "REVERSE", text: "대화 속에서 아이디어가 나온다." },
  { id: 51, axis: "ENERGY", group: "REVERSE", text: "혼자보다 함께할 때 더 잘한다." },
  { id: 52, axis: "ENERGY", group: "REVERSE", text: "생각은 말하면서 정리된다." },
  { id: 53, axis: "ENERGY", group: "REVERSE", text: "사람들의 반응이 중요하다." },
  { id: 54, axis: "ENERGY", group: "REVERSE", text: "외부 활동이 많을수록 활력이 생긴다." },
  { id: 55, axis: "ENERGY", group: "REVERSE", text: "혼자 오래 있으면 답답하다." },
  { id: 56, axis: "ENERGY", group: "REVERSE", text: "네트워크가 성장의 핵심이다." },
  { id: 57, axis: "ENERGY", group: "REVERSE", text: "영향력을 넓히는 게 중요하다." },
  { id: 58, axis: "ENERGY", group: "REVERSE", text: "무대나 사람 앞에서 힘이 난다." },
  { id: 59, axis: "ENERGY", group: "REVERSE", text: "행동과 소통이 에너지원이다." },
  { id: 60, axis: "ENERGY", group: "REVERSE", text: "혼자보다는 함께할 때 성과가 난다." },
  { id: 61, axis: "ENERGY", group: "SITUATION", text: "문제를 혼자 정리해 해결한다." },
  { id: 62, axis: "ENERGY", group: "SITUATION", text: "깊이 공부해 성장하는 편이다." },
  { id: 63, axis: "ENERGY", group: "SITUATION", text: "막히면 혼자 생각하며 푼다." },
  { id: 64, axis: "ENERGY", group: "SITUATION", text: "구조를 혼자 만든 뒤 공유한다." },
  { id: 65, axis: "ENERGY", group: "SITUATION", text: "혼자 쉬며 에너지를 회복한다." },
  { id: 66, axis: "ENERGY", group: "SITUATION", text: "결정 전 혼자 숙고가 필요하다." },
  { id: 67, axis: "ENERGY", group: "SITUATION", text: "실력을 먼저 쌓고 드러낸다." },
  { id: 68, axis: "ENERGY", group: "SITUATION", text: "스트레스는 혼자 풀어야 한다." },
  { id: 69, axis: "ENERGY", group: "SITUATION", text: "내공이 기회라고 느낀다." },
  { id: 70, axis: "ENERGY", group: "SITUATION", text: "완성도를 높인 뒤 세상에 낸다." },
  { id: 71, axis: "ENERGY", group: "SITUATION", text: "고독한 몰입을 선호한다." },
  { id: 72, axis: "ENERGY", group: "SITUATION", text: "분석과 정리가 먼저다." },
  
  // VALUE 73-108
  { id: 73, axis: "VALUE", group: "STANDARD", text: "돈보다 의미가 더 중요하다." },
  { id: 74, axis: "VALUE", group: "STANDARD", text: "선택의 기준은 가치에 있다." },
  { id: 75, axis: "VALUE", group: "STANDARD", text: "인정받지 않아도 의미 있으면 한다." },
  { id: 76, axis: "VALUE", group: "STANDARD", text: "성과가 늦어도 방향이 중요하다." },
  { id: 77, axis: "VALUE", group: "STANDARD", text: "기여할 때 만족을 느낀다." },
  { id: 78, axis: "VALUE", group: "STANDARD", text: "돈은 수단에 가깝다." },
  { id: 79, axis: "VALUE", group: "STANDARD", text: "의미 없는 일은 오래 못 한다." },
  { id: 80, axis: "VALUE", group: "STANDARD", text: "무엇을 남길지 자주 생각한다." },
  { id: 81, axis: "VALUE", group: "STANDARD", text: "가치 있다면 손해도 감수한다." },
  { id: 82, axis: "VALUE", group: "STANDARD", text: "의미 있는 일은 에너지를 준다." },
  { id: 83, axis: "VALUE", group: "STANDARD", text: "성공의 기준은 의미다." },
  { id: 84, axis: "VALUE", group: "STANDARD", text: "사람에게 도움이 되는 일에 끌린다." },
  { id: 85, axis: "VALUE", group: "REVERSE", text: "결과 없으면 의미도 없다." },
  { id: 86, axis: "VALUE", group: "REVERSE", text: "돈 안 되면 지속할 이유 없다." },
  { id: 87, axis: "VALUE", group: "REVERSE", text: "인정받아야 의미가 커진다." },
  { id: 88, axis: "VALUE", group: "REVERSE", text: "성과가 빨라야 옳다." },
  { id: 89, axis: "VALUE", group: "REVERSE", text: "보상이 삶의 만족을 준다." },
  { id: 90, axis: "VALUE", group: "REVERSE", text: "돈이 목표가 될 때가 많다." },
  { id: 91, axis: "VALUE", group: "REVERSE", text: "수익 없으면 결국 포기한다." },
  { id: 92, axis: "VALUE", group: "REVERSE", text: "남는 게 없으면 허무하다." },
  { id: 93, axis: "VALUE", group: "REVERSE", text: "손해 감수는 비현실적이다." },
  { id: 94, axis: "VALUE", group: "REVERSE", text: "보상이 있어야 힘이 난다." },
  { id: 95, axis: "VALUE", group: "REVERSE", text: "성과가 기준이다." },
  { id: 96, axis: "VALUE", group: "REVERSE", text: "내 성취가 우선이다." },
  { id: 97, axis: "VALUE", group: "SITUATION", text: "의미가 크면 돈이 적어도 선택한다." },
  { id: 98, axis: "VALUE", group: "SITUATION", text: "가치관 맞는 일을 고른다." },
  { id: 99, axis: "VALUE", group: "SITUATION", text: "조회수보다 메시지를 중시한다." },
  { id: 100, axis: "VALUE", group: "SITUATION", text: "성장에 도움 되는 시간을 쓴다." },
  { id: 101, axis: "VALUE", group: "SITUATION", text: "이유를 묻는다면 가치라고 답한다." },
  { id: 102, axis: "VALUE", group: "SITUATION", text: "미션 중심 커리어를 택한다." },
  { id: 103, axis: "VALUE", group: "SITUATION", text: "가치관 맞는 파트너를 고른다." },
  { id: 104, axis: "VALUE", group: "SITUATION", text: "성공은 의미 있는 삶이다." },
  { id: 105, axis: "VALUE", group: "SITUATION", text: "원칙을 지키는 편이다." },
  { id: 106, axis: "VALUE", group: "SITUATION", text: "임팩트를 보고 투자한다." },
  { id: 107, axis: "VALUE", group: "SITUATION", text: "의미가 있어 계속한다." },
  { id: 108, axis: "VALUE", group: "SITUATION", text: "사람에게 도움 되는 쪽을 고른다." },
  
  // STRATEGY 109-144
  { id: 109, axis: "STRATEGY", group: "STANDARD", text: "예측 가능한 루틴이 필요하다." },
  { id: 110, axis: "STRATEGY", group: "STANDARD", text: "지속 가능성이 중요하다." },
  { id: 111, axis: "STRATEGY", group: "STANDARD", text: "리스크는 줄이고 싶다." },
  { id: 112, axis: "STRATEGY", group: "STANDARD", text: "속도보다 안정이 맞다." },
  { id: 113, axis: "STRATEGY", group: "STANDARD", text: "작은 개선을 오래 한다." },
  { id: 114, axis: "STRATEGY", group: "STANDARD", text: "실패 가능성이 크면 피한다." },
  { id: 115, axis: "STRATEGY", group: "STANDARD", text: "급격한 변화는 부담된다." },
  { id: 116, axis: "STRATEGY", group: "STANDARD", text: "운영과 관리에 강하다." },
  { id: 117, axis: "STRATEGY", group: "STANDARD", text: "감당 범위 안에서 움직인다." },
  { id: 118, axis: "STRATEGY", group: "STANDARD", text: "느려도 안정적이면 괜찮다." },
  { id: 119, axis: "STRATEGY", group: "STANDARD", text: "균형이 깨지는 게 두렵다." },
  { id: 120, axis: "STRATEGY", group: "STANDARD", text: "계획된 환경이 편하다." },
  { id: 121, axis: "STRATEGY", group: "REVERSE", text: "안정은 성장을 막는다." },
  { id: 122, axis: "STRATEGY", group: "REVERSE", text: "빠르게 커져야 한다." },
  { id: 123, axis: "STRATEGY", group: "REVERSE", text: "큰 기회면 위험을 감수한다." },
  { id: 124, axis: "STRATEGY", group: "REVERSE", text: "폭발적 성장을 선호한다." },
  { id: 125, axis: "STRATEGY", group: "REVERSE", text: "큰 도전이 삶을 바꾼다." },
  { id: 126, axis: "STRATEGY", group: "REVERSE", text: "시도하지 않으면 손해다." },
  { id: 127, axis: "STRATEGY", group: "REVERSE", text: "변화가 빠를수록 좋다." },
  { id: 128, axis: "STRATEGY", group: "REVERSE", text: "확장이 내 성향이다." },
  { id: 129, axis: "STRATEGY", group: "REVERSE", text: "범위를 넓히는 게 성장이다." },
  { id: 130, axis: "STRATEGY", group: "REVERSE", text: "느린 성장은 답답하다." },
  { id: 131, axis: "STRATEGY", group: "REVERSE", text: "균형보다 성장이 낫다." },
  { id: 132, axis: "STRATEGY", group: "REVERSE", text: "기회면 즉시 전환한다." },
  { id: 133, axis: "STRATEGY", group: "SITUATION", text: "안정적 수입보다 성장 가능성을 본다." },
  { id: 134, axis: "STRATEGY", group: "SITUATION", text: "작게 오래보다 빠른 확장을 택한다." },
  { id: 135, axis: "STRATEGY", group: "SITUATION", text: "빠르게 팀을 꾸린다." },
  { id: 136, axis: "STRATEGY", group: "SITUATION", text: "넓게 배우는 편이다." },
  { id: 137, axis: "STRATEGY", group: "SITUATION", text: "빠른 출시를 선호한다." },
  { id: 138, axis: "STRATEGY", group: "SITUATION", text: "손실보다 상한을 본다." },
  { id: 139, axis: "STRATEGY", group: "SITUATION", text: "도전을 우선한다." },
  { id: 140, axis: "STRATEGY", group: "SITUATION", text: "실패를 감수한다." },
  { id: 141, axis: "STRATEGY", group: "SITUATION", text: "기회면 바로 움직인다." },
  { id: 142, axis: "STRATEGY", group: "SITUATION", text: "큰 목표를 세운다." },
  { id: 143, axis: "STRATEGY", group: "SITUATION", text: "성장에 자원을 쓴다." },
  { id: 144, axis: "STRATEGY", group: "SITUATION", text: "검증 전에도 전환한다." },
];
